export const ApiRoutes = {
  GET_PARTNER: "/api/v1/person",
  GET_PARTNER_COUNT: "/api/v1/person/count",
  GET_ENTRY_COUNT: "/api/v1/entry/count",
  GET_ENTRY_TYPES: "/api/v1/entry/types",
  GET_ENTRY_AMOUNTS: "/api/v1/entry/amounts",
  POST_ENTRY: "/api/v1/entry",
  GET_LOAN_COUNT: "/api/v1/loan/count",
  POST_LOAN: "/api/v1/loan",
  GET_ENTRIES: "/api/v1/entry",
  GET_ENTRY_DETAIL: "/api/v1/entry/detail",
  GET_LOAN: "/api/v1/loan",
  GET_LOAN_DETAIL: "/api/v1/loan/detail",
  GET_EGRESS_COUNT: "/api/v1/egress/count",
  POST_EGRESS: "/api/v1/egress",
  GET_EGRESS: "/api/v1/egress",
  GET_EGRESS_DETAIL: "/api/v1/egress/detail",
  POST_PARTNER: "/api/v1/person",
  PUT_PARTNER: "/api/v1/person",
  DELETE_PARTNER: "/api/v1/person",
  GET_METRICS: "/api/v1/metrics",
  GET_TYPES_METRICS: "/api/v1/metrics/types",
  GET_CONTRIBUTIONS: "/api/v1/entry/contribution",
};
