export enum ComponentsLabels {
  LOAN_MODAL_TITLE = "DETALLE DE CRÉDITO",
  PARTNER = "Socio:",
  PAY = "Pagar",
  TH_LOAN_FEE = "Cuota",
  TH_LOAN_DATE = "Fecha de Pago",
  TH_LOAN_FEE_VALUE = "Cuota Capital",
  TH_LOAN_INTEREST = "Interes",
  TH_LOAN_TOTAL = "Total a Pagar",
  TH_LOAN_BALANCE = "Saldo",
  TH_LOAN_ACTION = "Acción",
  ENTRY_MODAL_TITLE = "COMPROBANTE DE INGRESO",
  DATE = "Fecha:",
  TYPE = "Medio:",
  TYPE_TRANSFER = "Transferencia",
  TYPE_CASH = "Efectivo",
  AMOUNT = "Monto:",
  TH_ENTRY_TYPE = "Por concepto de",
  TH_ENTRY_VALUE = "Valor",
  CLOSE = "Cerrar",
  PRINT = "Imprimir",
  INTEREST = "Interes (Mensual):",
  DEBT = "Deuda:",
  MONTHS = "Meses:",
  PRE_CANCEL = "Precancelar",
  SAVE = "Guardar",
  EGRESS_MODAL_TITLE = "COMPROBANTE DE EGRESO",
}
