export enum LoanUpdateLabels {
  TITLE = "ABONAR PAGO AL CRÉDITO",
  SUB_TITLE_1 = "Tabla de Amortización actual",
  SUB_TITLE_2 = "Calcular Abono",
  DEBTOR = "Deudor:",
  AMOUNT = "Monto:",
  MONTHS = "Meses:",
  DEBT = "Deuda:",
  INTEREST = "Interes:",
  CALC_TYPE = "Cálculo:",
  CALC_TYPE_1 = "mantener valor de cuota / reducir número de cuotas",
  CALC_TYPE_2 = "reducir valor de cuota / mantener número de cuotas",
  NEW_AMOUNT = "Nuevo Capital:",
  SUCCESS_UPDATE_MODAL_TITLE = "Crédito actualizado correctamente",
  SUCCESS_UPDATE_MODAL_SUBTITLE = "Desea imprimir la nueva tabla de amortización?",
}
