export enum LoanLabels {
  TITLE = "CEPO DE ORO",
  SUB_TITLE = "Creación de Crédito",
  SUCCESS_SAVE_MODAL_TITLE = "Credito guardado correctamente",
  SUCCESS_SAVE_MODAL_MESSAGE = "Desea Imprimir la tabla?",
  CLOSE = "Cerrar",
  PRINT = "Imprimir",
  DATE = "Fecha:",
  INTEREST = "Interes:",
  DEBTOR = "Deudor:",
  MONTHS = "Meses:",
  VALUE = "Valor:",
  GUARANTOR1 = "Garante 1:",
  GUARANTOR2 = "Garante 2:",
  FEE_TYPE = "Tipo de Cuota:",
  FEE_TYPE_FIXED = "Fijo",
  FEE_TYPE_VARIABLE = "Variable",
  SAVE = "Guardar",
  CALCULATE = "Calcular",
}
